# Generated by Django 3.2.6 on 2021-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yerba',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
