# Generated by Django 3.2.6 on 2021-09-04 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0006_auto_20210904_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('firma', models.CharField(max_length=200)),
                ('nazwa', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('białe', 'białe'), ('czerwone', 'czerwone'), ('różowe', 'różowe')], default='białe', max_length=32)),
                ('kolor', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('klarowność', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('musowanie', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('aromat', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('moc', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('nuty_owocowe', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('ocena', models.FloatField(choices=[(0.0, '0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5'), (5.5, '5.5'), (6.0, '6'), (6.5, '6.5'), (7.0, '7'), (7.5, '7.5'), (8.0, '8'), (8.5, '8.5'), (9.0, '9'), (9.5, '9.5'), (10.0, '10')], default=0)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
