# Generated by Django 3.2.6 on 2021-09-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0008_kawa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kawa',
            name='robusta',
        ),
    ]
