# Generated by Django 3.2.7 on 2021-09-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0012_auto_20210907_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wino',
            name='nuty_owocowe',
        ),
    ]
