# Generated by Django 3.2.7 on 2021-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0013_remove_wino_nuty_owocowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='wino',
            name='nuty_cytrusowe',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_czarnych_owoców',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_czerwonych_owoców',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_dojrzewające',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_drożdżowe',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_dębowe',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_kwiatowe',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_maślane',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_minerałów',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_pestkowców',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_przypraw',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_roślinne',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_suszonych_owoców',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_tropikalne',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_zielonych_owoców',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
        migrations.AddField(
            model_name='wino',
            name='nuty_ziemne',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='nie', max_length=32),
        ),
    ]
