# Generated by Django 3.2.7 on 2021-09-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_auto_20210911_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wino',
            name='nuty_przypraw',
        ),
    ]
