# Generated by Django 3.2.6 on 2021-09-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_remove_wino_nuty_przypraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='wino',
            name='zawartość_cukru',
            field=models.CharField(choices=[('wytrawne', 'wytrawne'), ('półwytrawne', 'półwytrawne'), ('półsłodkie', 'półsłodkie'), ('słodkie', 'słodkie')], default='wytrawne', max_length=32),
        ),
    ]
