# Generated by Django 3.2.6 on 2021-12-20 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0017_piwo_styl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('zatwierdzony', models.BooleanField(default=False)),
            ],
        ),
    ]
